### ISSUE TITLE
请问一直卡在禁止🚫图标怎么解决

### ISSUE THREAD

**Issue by wooxi** [AlphaGHX/Hackintosh-CVN-b460i-efi#1]
一样的配置，i5 10400+七彩虹 cvn b460i v20，试了黑果小兵的镜像，big  sur  11.1会卡在禁止图标，11.2会卡在苹果logo,请问有没有解决办法

**Comment by AlphaGHX** [comment]
先确保bios设置正确。在开机选项哪里，清除一下nvram。如果卡在🚫图标请多等一下，这个问题之前在我安装的时候也出现过，很奇怪。如果你觉得等待时间过长，你可以按照下图开-v并展示出你卡在哪里。
你可以用Telegram联系我：https://t.me/Alpha_TL
<img width="979" alt="2FE88917-4440-481F-B19F-3EF17A1B7917" src="https://user-images.githubusercontent.com/61853980/110348750-efa01080-806c-11eb-8151-240bacb02abe.png">

**Comment by AlphaGHX** [comment]
已解决，如果出现禁止图标等一系列问题，可以尝试更换镜像来解决。
