### ISSUE TITLE
请您帮忙更新下OC到0.74好吗？

### ISSUE THREAD

**Issue by mythgp** [AlphaGHX/Hackintosh-CVN-b460i-efi#10]
用了您的OC，感觉非常棒，感谢您的制作。我想尝试升级下12.01.希望您能够帮忙升级下OC版本至最新版，谢谢！

**Comment by AlphaGHX** [comment]
> 用了您的OC，感觉非常棒，感谢您的制作。我想尝试升级下12.01.希望您能够帮忙升级下OC版本至最新版，谢谢！

如果我有时间，最早会在本周二更新。
