### ISSUE TITLE
CVN B560

### ISSUE THREAD

**Issue by luhua98989898** [AlphaGHX/Hackintosh-CVN-b460i-efi#11]
大佬，我的是B560的七彩虹，不知道能不能套用B460的引导

**Comment by AlphaGHX** [comment]
因为这个EFI是针对10代U配置，如果你是10代U，有可能可以。但是USB可能有问题，你需要重新定制USB。

**Comment by AlphaGHX** [comment]
> 大佬，我的是B560的七彩虹，不知道能不能套用B460的引导

因为这个EFI是针对10代U配置，如果你是10代U，有可能可以。但是USB可能有问题，你需要重新定制USB。
