### ISSUE TITLE
10400f+免驱卡rx6600xt安装的时候跑完代码黑屏

### ISSUE THREAD

**Issue by captxiaoxiao** [AlphaGHX/Hackintosh-CVN-b460i-efi#12]
已经添加了pikara代码，还是跑完代码就黑屏。自己配的efi和大佬的efi都一样，大佬有啥思路没呀。

**Comment by AlphaGHX** [comment]
不好意思，我没研究过独显。我就用来敲代码的，所以用的核显。

**Comment by duzhuoshanwai** [comment]
我的5500xt也是这样 卡诺基三星颗粒自己刷了个vbios可以支持uefi启动
在bios里面设置
关闭csm
internal graphics auto改成enable
me control 改成enable
用ocat工具
agdpmod=pikera 添加这个 在 boot-args下面
