### ISSUE TITLE
用i3 10105 按这个教程可以直接成功吗 需要修改其他什么吗

### ISSUE THREAD

**Issue by barry-eng** [AlphaGHX/Hackintosh-CVN-b460i-efi#13]

**Comment by AlphaGHX** [comment]
只要是同主板大概率就没问题。cpu的话他是自动适配的。

**Comment by barry-eng** [comment]
可以提供一下镜像吗 466321949@qq.com

**Comment by AlphaGHX** [comment]
> 可以提供一下镜像吗 [466321949@qq.com](mailto:466321949@qq.com)

请查看本页最后一部分 [链接](https://github.com/AlphaGHX/Hackintosh-CVN-b460i-efi#%E6%84%9F%E8%B0%A2)

**Comment by barry-eng** [comment]
可以更新12.3.1

**Comment by barry-eng** [comment]
吗

**Comment by AlphaGHX** [comment]
> 可以更新12.3.1

可以

**Comment by barry-eng** [comment]
已经安装12.4 感谢 就是hdmi唤醒有问题 还有连接WiFi提示需要wpa2密码 可以练手机热点

**Comment by barry-eng** [comment]
kernel 里面好像多加了 加触摸板驱动...  缓冲帧不完整
