### ISSUE TITLE
您好，Big sur11.7 关机不断电请问有办法么？

### ISSUE THREAD

**Issue by Hymwgk** [AlphaGHX/Hackintosh-CVN-b460i-efi#14]
用的是您的release里面针对Big Sur的EFI

**Comment by Hymwgk** [comment]
然后主板CVN B460i  应该和您是一样的； 没有独显

**Comment by Hymwgk** [comment]
现在是关了机   电源一直断不了电，不知道为什么

**Comment by AlphaGHX** [comment]
尝试重置 bios 和 nvram。因为我没遇到此情况，所以也没啥针对性的办法。建议去网上找找，如果中文搜索没啥解决方案，可以用英文在谷歌搜。

**Comment by Hymwgk** [comment]
好的谢谢，我试下恢复默认bios设置

**Comment by Hymwgk** [comment]
恢复默认bios之后，关机没有问题了，谢谢～
