### ISSUE TITLE
不知道有没有碰到过关机后usb不断电，重启总是要一直卡再10%进度，强关后再开才能进系统

### ISSUE THREAD

**Issue by chrisyekui** [AlphaGHX/Hackintosh-CVN-b460i-efi#15]
不知道有没有碰到过关机后usb不断电，重启总是要一直卡再10%进度，强关后再开才能进系统

**Comment by chrisyekui** [comment]
之前bigsur没这种问题

**Comment by AlphaGHX** [comment]
> 不知道有没有碰到过关机后usb不断电，重启总是要一直卡再10%进度，强关后再开才能进系统

目前我在使用 Ventura 并没有你说的问题。你可以尝试：重置 BIOS 和 nvram。并且这次更新我是没有兼容自带网卡的，有没有正确加载驱动？有没有删除 Brcm 那些驱动？

**Comment by chrisyekui** [comment]
> > 不知道有没有碰到过关机后usb不断电，重启总是要一直卡再10%进度，强关后再开才能进系统
> 
> 目前我在使用 Ventura 并没有你说的问题。你可以尝试：重置 BIOS 和 nvram。并且这次更新我是没有兼容自带网卡的，有没有正确加载驱动？有没有删除 Brcm 那些驱动？

我用的也是Brcm的网卡，目前怀疑可能跟我使用的2.4g接收器鼠标有关，我换成有线鼠标后，重启几次没再重现这个问题，是否真解决还得再观察一下

**Comment by chrisyekui** [comment]
> > 不知道有没有碰到过关机后usb不断电，重启总是要一直卡再10%进度，强关后再开才能进系统
> 
> 目前我在使用 Ventura 并没有你说的问题。你可以尝试：重置 BIOS 和 nvram。并且这次更新我是没有兼容自带网卡的，有没有正确加载驱动？有没有删除 Brcm 那些驱动？

我用的也是Brcm的网卡，目前怀疑可能跟我使用的2.4g接收器鼠标有关，我换成有线鼠标后，重启几次没再重现这个问题，是否真解决还得再观察一下
