### ISSUE TITLE
原生网卡+蓝牙的efi（顺带加了个radeon boost的kext）

### ISSUE THREAD

**Issue by YAcornY** [AlphaGHX/Hackintosh-CVN-b460i-efi#16]
我在版主的基础上补做了一个支持原生ax200的顺便带了个免驱卡的radoen boost链接如下
https://www.aliyundrive.com/s/eQuLqQAbAt4

**Comment by AlphaGHX** [comment]
感谢你帮忙改进，请问一下 radoen boost 有什么作用？

**Comment by YAcornY** [comment]
> 感谢你帮忙改进，请问一下 radoen boost 有什么作用？

打错了应该是radeon boost哈哈哈哈哈哈，http://imacos.top/2022/02/09/1103-2/可以参考这个网站的描述，不过随着版本更新有些a卡无法支持，但是注入不影响开机和正常使用，不过macos13使用不知道有没有提升，不过注入这个kext不影响正常使用，干脆放里面死马当活马医（手动滑稽）

**Comment by YAcornY** [comment]
> 感谢你帮忙改进，请问一下 radoen boost 有什么作用？

打错了应该是radeon boost哈哈哈哈哈哈，[http://imacos.top/2022/02/09/1103-2/
可以参考这个网站的描述，不过随着版本更新有些a卡无法支持，但是注入不影响开机和正常使用，不过macos13使用不知道有没有提升，不过注入这个kext不影响正常使用，干脆放里面死马当活马医（手动滑稽）](http://imacos.top/2022/02/09/1103-2/%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E7%9A%84%E6%8F%8F%E8%BF%B0%EF%BC%8C%E4%B8%8D%E8%BF%87%E9%9A%8F%E7%9D%80%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E6%9C%89%E4%BA%9Ba%E5%8D%A1%E6%97%A0%E6%B3%95%E6%94%AF%E6%8C%81%EF%BC%8C%E4%BD%86%E6%98%AF%E6%B3%A8%E5%85%A5%E4%B8%8D%E5%BD%B1%E5%93%8D%E5%BC%80%E6%9C%BA%E5%92%8C%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A8%EF%BC%8C%E4%B8%8D%E8%BF%87macos13%E4%BD%BF%E7%94%A8%E4%B8%8D%E7%9F%A5%E9%81%93%E6%9C%89%E6%B2%A1%E6%9C%89%E6%8F%90%E5%8D%87%EF%BC%8C%E4%B8%8D%E8%BF%87%E6%B3%A8%E5%85%A5%E8%BF%99%E4%B8%AAkext%E4%B8%8D%E5%BD%B1%E5%93%8D%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A8%EF%BC%8C%E5%B9%B2%E8%84%86%E6%94%BE%E9%87%8C%E9%9D%A2%E6%AD%BB%E9%A9%AC%E5%BD%93%E6%B4%BB%E9%A9%AC%E5%8C%BB%EF%BC%88%E6%89%8B%E5%8A%A8%E6%BB%91%E7%A8%BD%EF%BC%89)

**Comment by KonBAI-Q** [comment]
> 我在版主的基础上补做了一个支持原生ax200的顺便带了个免驱卡的radoen boost链接如下 https://www.aliyundrive.com/s/eQuLqQAbAt4

我改了AirportItlwm.kext（v2.2.0-alpha）驱动后，一开wifi会直接死机，重启。请问是要做什么额外操作吗？
