### ISSUE TITLE
睡眠偶尔风扇狂转

### ISSUE THREAD

**Issue by UzkiS** [AlphaGHX/Hackintosh-CVN-b460i-efi#18]
我的机器睡眠偶尔风扇最大速狂转，不知道是不是我个体问题，我用自己适配的EFI和该EFI都会偶尔出现该情况，想问问大家会吗

**Comment by AlphaGHX** [comment]
我的 CPU 风扇到没问题，独显风扇偶尔狂转，网上也有很多类似的反馈。暂时无解（开玩笑，根本就是无解）。转白果 or 转 win 吧。

**Comment by UzkiS** [comment]
我现在怀疑是显示器和DW1820A的问题，我再研究研究
