### ISSUE TITLE
引导问题

### ISSUE THREAD

**Issue by fengboyboy** [AlphaGHX/Hackintosh-CVN-b460i-efi#2]
你好，我用了你分享的这个引导，同配置。
发现在第一次开机启动的时候UHD630驱动有问题，需按重启键重新启动才会正确驱动显卡

**Comment by AlphaGHX** [comment]
能给出这个问题具体表现在哪里吗？

**Comment by fengboyboy** [comment]
这个我得重新测试下，抓一下信息才行。晚上我试试

**Comment by fengboyboy** [comment]
<img width="555" alt="WechatIMG18" src="https://user-images.githubusercontent.com/6865053/112401986-a2978c00-8d46-11eb-924e-bf6b26f5311b.png">
<img width="615" alt="WechatIMG19" src="https://user-images.githubusercontent.com/6865053/112401990-a4614f80-8d46-11eb-900b-cef67cc3b463.png">

第一个图是首次启动，屏幕是冻住的效果。通过远程登录截图的显卡信息

第二个图是重启后的截图信息，是完全正常的。

**Comment by AlphaGHX** [comment]
你装的是Catalina，同时你也改了下EFI机型和显存大小。我之前机型改成Mac mini的时候用hdmi会无信号，之后改成iMac19就好了。不知道是不是这个原因。如果不是这个原因呢，我几乎也没法帮你，毕竟我没遇到此问题。

**Comment by fengboyboy** [comment]
好的，感谢。
