### ISSUE TITLE
七彩虹b460i + i5 10500 +西数 SN750 1T + 显卡Nvidia K2000，第二阶段无限重启

### ISSUE THREAD

**Issue by NormanBeta** [AlphaGHX/Hackintosh-CVN-b460i-efi#3]
用的是楼主提供的OC 替换了 黑苹果小兵 macOS Big Sur 11.1 20C69 Installer for CLOVER 5127 and OpenCore 0.6.4 and PE，第一阶段安装差12分钟重启，然后进入第二阶段出苹果后就重启

**Comment by NormanBeta** [comment]
bios 设置除了楼主的设置，还有下面的
设置 | 设置
-- | --
高级模式->高级->C状态 | 关闭
高级模式->高级->CSM支持 | 关闭
高级模式->高级->超线程 | 启动
高级模式->高级->英特尔虚拟化技术 | 启动
高级模式->高级->XHCI交接 | 启动
高级模式->高级->SATA模式 | AHCI
高级模式->主板芯片组->ME控制 | 关闭
高级模式->引导->Bios写保护 | 关闭

**Comment by AlphaGHX** [comment]
这个EFI完全没考虑独显，不知道是不是独显的问题。请开-v然后附上卡在哪里进TG群问下。[黑果小兵TG群](https://t.me/macos_installer)

**Comment by NormanBeta** [comment]
我把显卡拔了再装一遍试试，抓下-v

**Comment by NormanBeta** [comment]
第二阶段不重启了，但进度条一直不动，一直还剩下29分钟

**Comment by NormanBeta** [comment]
换了个引导盘，mac安装系统格式设为APFS，顺利安装，然后直接插上K2000免驱
