### ISSUE TITLE
无法airdrop

### ISSUE THREAD

**Issue by lvshouyang** [AlphaGHX/Hackintosh-CVN-b460i-efi#5]
配置很类似使用了老哥的efi第一次安装就成功了，非常感谢，目前ax200测试网速。我家200m联通，win可以到230，这个可以到180，非常好了，蓝牙也正常，定位慢点，但是也正常，就差 隔空投送，希望后续老哥有更新

**Comment by wuweic9658** [comment]
> 配置很像使用了老哥的efi第一次安装就成功了，非常感谢，现在ax200测试网速。我家200m联通，win可以到230，这个可以到180，非常好，蓝牙也正常，慢点，但也不错，就差隔空投送，希望老哥有更新

请问你的睡眠唤醒可以吗？我的睡眠后就没法唤醒了

**Comment by AlphaGHX** [comment]
> > 配置很像使用了老哥的efi第一次安装就成功了，非常感谢，现在ax200测试网速。我家200m联通，win可以到230，这个可以到180，非常好，蓝牙也正常，慢点，但也不错，就差隔空投送，希望老哥有更新
> 
> 请问你的睡眠唤醒可以吗？我的睡眠后就没法唤醒了

这个因为本人技术力有限，还没解决。暑假我更新一下OC，然后再查查能不能解决。最近有点忙。

**Comment by wuweic9658** [comment]
> > > 配置很像使用了老哥的efi第一次安装就成功了，非常感谢，现在ax200测试网速。我家200米联通，win可以到230这个，可以到180，非常好，蓝牙也正常，慢点，但也不错，就差隔空投送，希望老哥有更新
> > 
> > 
> > 你的睡眠唤醒可以吗？我的睡眠后就可以唤醒了吗？
> 
> 这个因为自己技术力有限，还没解决。暑假我更新OC，然后再查查不能解决。最近有点忙。

好的，好的感谢大佬

**Comment by AlphaGHX** [comment]
能力有限，暂时无法修复。
