### ISSUE TITLE
我卡在这个界面了，没法动了

### ISSUE THREAD

**Issue by braveheart4217** [AlphaGHX/Hackintosh-CVN-b460i-efi#6]
![微信图片_20210705012419](https://user-images.githubusercontent.com/9996013/124379955-ba3ec300-dcec-11eb-9ff2-79f693e727f9.jpg)

**Comment by braveheart4217** [comment]
主机信息： 七彩虹b460i + i5 10400 + 铠侠RC10 500G

**Comment by AlphaGHX** [comment]
兄弟，这是连接你的鼠标，你已经安装成功了
