### ISSUE TITLE
您好，感谢您提供的efi文件，但是我有个问题想请教您，当我接上120刷新率的屏幕时出现了严重的跳帧现象，实际帧率直接减半了，请问您有好的解决办法吗？

### ISSUE THREAD

**Issue by mistgod** [AlphaGHX/Hackintosh-CVN-b460i-efi#7]

**Comment by AlphaGHX** [comment]
据我了解，macOS对UHD630这个核显优化的有些问题，如果你使用的是高分辨率屏幕，有可能出现卡顿现象。目前我已知1080p144hz和2k60hz还是挺流畅的。不知道你的分辨率是多少。

**Comment by mistgod** [comment]
> 据我了解，macOS对UHD630这个核显优化的有些问题，如果你使用的是高分辨率屏幕，有可能出现卡顿现象。目前我已知1080p144hz和2k60hz还是挺流畅的。不知道你的分辨率是多少。

不好意思大佬，这几天有点事没看消息，我的屏幕是1080p120hz的，我试着用hackintool重新搞了显卡驱动，但是好像直接进不去了

**Comment by AlphaGHX** [comment]
> 不好意思大佬，这几天有点事没看消息，我的屏幕是1080p120hz的，我试着用hackintool重新搞了显卡驱动，但是好像直接进不去了

1080p120hz的话，UDH630能带的挺流畅的，而且这个EFI是能驱动UDH630的。如果你使用的和我同样的主板，也是10代酷睿，那我就不清楚到底是什么引起的了。

**Comment by mistgod** [comment]
> > 不好意思大佬，这几天有点事没看消息，我的屏幕是1080p120hz的，我试着用hackintool重新搞了显卡驱动，但是好像直接进不去了
> 
> 
> 
> 1080p120hz的话，UDH630能带的挺流畅的，而且这个EFI是能驱动UDH630的。如果你使用的和我同样的主板，也是10代酷睿，那我就不清楚到底是什么引起的了。
> 
> 

好的，没事，我在摸索摸索，谢谢大佬了。
