### ISSUE TITLE
七彩虹更新了BIOS，BIOS支持关闭CFG lock，休眠已经正常了

### ISSUE THREAD

**Issue by kuaner** [AlphaGHX/Hackintosh-CVN-b460i-efi#8]
感谢大大的efi，最近七彩虹更新了bios，可以手动关闭cfg lock了，经过测试，休眠已经正常了

**Comment by AlphaGHX** [comment]
我更新了bios关闭了cfg，然后在efi里吧AppleXcpmCfgLock关了（这个相当于强制关闭cfg，更新bios之前必开的）。但是那个问题依旧在：睡眠唤醒后，某些应用，比如hackintool，vs code，iina这些应用无法打开，打开就是无响应。请你测试一下，你那边正常吗？

**Comment by kuaner** [comment]
乌龙了，确实还有问题，感觉很诡异

**Comment by AlphaGHX** [comment]
可惜了，只能等官方后续BIOS的更新了，或者放弃这块主板。
